function [c,k,a,b]=alg_xrusou_tomea(f,l,a,b)
k=1;
g=0.618;
x1=a+(1-g)*(b-a);
x2=a+g*(b-a);
y1=subs(f,{x1});
y2=subs(f,{x2});
c=2;
while((b-a)>=l)
    if(y1>y2)
        a=x1;
        x1=x2;
        y1=y2;
        x2=a+g*(b-a);
        y2=subs(f,{x2});
    elseif(y1<y2)
        b=x2;
        x2=x1;
        y2=y1;
        x1=a+(1-g)*(b-a);
        y1=subs(f,{x1});
    end
    c=c+1;
    k=k+1;
end
end
