function r=alg_quasiNewton2(e,co)
k=1;
r(:,k)=co;
D(:,:,k)=eye(2,2);
int=[0 1];
while(norm(gradf(r(1,k),r(2,k)))>=e)
    d(:,k)=-D(:,:,k)*gradf(r(1,k),r(2,k));
    g(k)=BisDeriv(e,int,r(:,k));
    r(:,k+1)=r(:,k)+g(k)*d(:,k);
    p(:,k)=r(:,k+1)-r(:,k);
    q(:,k)=gradf(r(1,k+1),r(2,k+1))-gradf(r(1,k),r(2,k));
    t(k)=q(:,k)'*D(:,:,k)*q(:,k);
    v(:,k)=(p(:,k)/(p(:,k)'*q(:,k)))-(D(:,:,k)*q(:,k))/t(k);
    D(:,:,k+1)=D(:,:,k)+(p(:,k)*p(:,k)')/(p(:,k)'*q(:,k))-...
    (D(:,:,k)*q(:,k)*q(:,k)'*D(:,:,k))/t(k)+(t(k)*v(:,k)*v(:,k)');
    if(~PosDef(D(:,:,k+1)))
        int(2)=int(2)+1;
        int(1)=int(1)-1;
        continue;
    else
        int(1)=0;
        int(2)=0.75;
    end
    k=k+1;
    if(k>100000)
        break;
    end
end
end