function r=alg_suz_klisewn3(e,co)
k=1;
r(:,k)=co;
g=0.5;
d=-gradf(r(1,k),r(2,k));
b=0;
r(:,k+1)=r(:,k)+g*d;
grad=gradf(r(1,k+1),r(2,k+1));
oldgrad=-d;
k=2;
while(norm(grad)>=e)
    b=(grad'*(grad-oldgrad))/(oldgrad'*oldgrad);
    d=-grad+b*d;
    if(k>=4)
        if(f(r(1,k),r(2,k))>0.9*f(r(1,k-3),r(2,k-3)))
            g=1.2*g;
        end
    end
    r(:,k+1)=r(:,k)+g*d;
    oldgrad=grad;
    grad=gradf(r(1,k+1),r(2,k+1));
    k=k+1;
    if(k>100000)
       break;
    end
end
end